#!/bin/bash
clear
Menu() {
    clear
    echo -e '\n'
   echo "      ==================================="
    echo "               OPEN VPN DATAMI (ROOT)     "
   echo "         ==================================="
    echo
    echo "            ESCOLHA UM APP PARA BAIXAR"
   echo "         ==================================="
    echo "              [ 1 ] - Escola em Casa DF"
    echo "              [ 2 ] - E-learning EC"
    echo "              [ 3 ] - Educa Olinda"
    echo "              [ 4 ] - Conecta Uneb"
    echo "              [ 5 ] - Sala Estudante SC"
    echo "              [ 6 ] - Minha Estacio"
    echo "              [ 7 ] - Conexão Escola"
    echo "              [ 8 ] - EscoLAR"
    echo "              [ 9 ] - Escola RS - Professor"
    echo "             [ 10 ] - Escola RS - Estudante"
    echo "             [ 11 ] - EDUCA SÃO LEO"
    echo "             [ 12 ] - Estude em Casa"
    echo "             [ 13 ] - Escola MSJ"
    echo "             [ 14 ] - Escola Igarassu"
    echo "             [ 15 ] - Princesa Educa+"
    echo "             [ 16 ] - ConquistApp"
    echo "             [ 17 ] - CMSP"
    echo "             [ 18 ] - Rio Educa Em Casa"
    echo "             [ 19 ] - Aulas Parana"
    echo "             [ 20 ] - Applique-se" 
    echo "             [ 21 ] - Voltar"
    echo "         ==================================="
    echo
    echo "ESCOLHA UMA OPÇÃO:"
    read App
    case $App in
    1) App="org.cordova.quasar.corona.app" ; atividade=".SplashScreenActivity" ; nome="EscolaDF" ; E1="1";;
    2) App="com.portoseguru.reach4all" ; atividade="com.datami.reachall.SplashScreen" ; nome="E-learning" ; E1="2";;
    3) App="org.educaolinda.app" ; atividade="org.aprendendosempre.app.main.MainActivity" ; nome="EducaOlinda" ; E1="3";;   
    4) App="com.conectauneb.reach4all" ; atividade="com.datami.reachall.SplashScreen" ; nome="ConectaUneb" ; E1="4";;
    5) App="br.sc.gov.ciasc.sed.inp" ; atividade=".MainActivity" ; nome="SalaEstudanteSC" ; E1="5";;
    8) App="br.gov.es.sedu.educacao" ; atividade=".MenuActivity" ; nome="EscoLAR" ; E1="8";;
    9) App="br.com.procergs.tuaescola" ; atividade=".MainActivity" ; nome="EscolaProfessorRS" ; E1="9";;
    10) App="br.com.procergs.estudante" ; atividade=".MainActivity" ; nome="EscolaEstudanteRS" ; E1="10";;
    11) App="com.educasaoleo.reach4all" ; atividade="com.educasaoleo.reachall.SplashScreen" ; nome="EducaSãoLeo" ; E1="11";;
    12) App="com.seduc.estudeemcasa" ; atividade=".SplashActivity" ; nome="EstudeEmCasa" ; E1="12";;
    13) App="com.escola.msj" ; atividade=".SplashScreenActivity" ; nome="EscolaMSJ" ; E1="13";;
    14) App="org.educarigarassu.app" ; atividade=".SplashScreenActivity" ; nome="EducarIguarassu" ; E1="14";;
    15) App="com.princesaeducamais" ; atividade=".SplashActivity" ; nome="PrincesaEducaMais" ; E1="15";;
    16) App="br.gov.ba.pmvc.vcapp" ; atividade=".SplashScreenActivity" ; nome="ConquistApp" ; E1="16";;    
    17) App="tv.ip.edusp" ; atividade="tv.ip.my.activities.SplashScreen" ; A3="su -c am start -n tv.ip.edusp/tv.ip.my.activities.VideoActivity2" ; nome="CentroDeMidiasSP" ; A2="su -c am start -n tv.ip.edusp/com.datami.smi.ui.VpnPermissionActivity" ; s="sleep 4" ; A4="su -c am start -n tv.ip.edusp/tv.ip.my.activities.SplashScreen" ; db="su -c pm disable tv.ip.edusp" ; eb="su -c pm enable tv.ip.edusp";E1="17";;
    18) App="tv.ip.rioeduca" ; atividade="tv.ip.my.activities.SplashScreen" ; A3="su -c am start -n tv.ip.rioeduca/tv.ip.my.activities.VideoActivity2" ; nome="RioEducaEmCasa" ; A2="su -c am start -n tv.ip.rioeduca/com.datami.smi.ui.VpnPermissionActivity" ; s="sleep 4" ; A4="su -c am start -n tv.ip.rioeduca/tv.ip.my.activities.SplashScreen" ; db="su -c pm disable tv.ip.rioeduca" ; eb="su -c pm enable tv.ip.rioeduca"; E1="18";;
    19) App="tv.ip.aulapr" ; atividade="tv.ip.my.activities.SplashScreen" ; A3="su -c am start -n tv.ip.aulapr/tv.ip.my.activities.VideoActivity2" ; nome="AulaParana" ; A2="su -c am start -n tv.ip.aulapr/com.datami.smi.ui.VpnPermissionActivity" ; s="sleep 4" ; A4="su -c am start -n tv.ip.aulapr/tv.ip.my.activities.SplashScreen" ; db="su -c pm disable tv.ip.aulapr" ; eb="su -c pm enable tv.ip.aulapr"; E1="19";;
    20) App="tv.ip.appliquese" ; atividade="tv.ip.my.activities.SplashScreen" ; A3="su -c am start -n tv.ip.appliquese/tv.ip.my.activities.VideoActivity2" ; nome="Applique-se" ; A2="su -c am start -n tv.ip.appliquese/com.datami.smi.ui.VpnPermissionActivity" ; s="sleep 4" ; A4="su -c am start -n tv.ip.appliquese/tv.ip.my.activities.SplashScreen" ; db="su -c pm disable tv.ip.appliquese" ; eb="su -c pm enable tv.ip.appliquese"; E1="20";;
    21) App21;;
    *) "Calma Barboleta" ; echo ; Menu;;
    esac
    connect
}

connect () {
clear
check(){
      appk=$(test -f "$HOME/$E1.apk" && echo 1)
    case $appk in
    1) clear ;;
    *) echo "BAIXANDO..." ; curl -sO https://raw.githubusercontent.com/luanwillianzh/vpn/main/$E1.apk && chmod +x $E1.apk && clear && echo "BAIXADO COM SUCESSO!" ; sleep 3 && clear  ;;
    esac
}
check
check(){
      apps=$(test -d "/data/data/$App" && echo 1)
    case $apps in
    1) echo "DESINSTALANDO SEU APP..." && su -c pm uninstall $App && echo ; echo "INSTALANDO O NOVO APP..." ; su -c pm install $HOME/$E1.apk ;;
    *) echo "INSTALANDO O NOVO APP..." ; su -c pm install $HOME/$E1.apk;;
     esac
}
check
sleep 2 && bash $HOME/vpn2/ovpnsu
}
App21(){
clear
bash $HOME/vpn2/ovpnsu
}
clear
Menu
